      
	SUBROUTINE SOLVER(NDIM,MPTR,IND,VAL,RHS,NNS,M_TYPE)	
      IMPLICIT NONE
      INTEGER NDIM,DIM,NNS,M_TYPE
	INTEGER ::PTR(NDIM+1),MPTR(NDIM+1),IND(NNS)
	DOUBLE PRECISION::VAL(NNS),RHS(NDIM)
      DIM=NDIM
	PTR(:)=MPTR(:)

      CALL GSS_demo_6(DIM,PTR,IND,VAL,RHS,M_TYPE)	
	
	END